var QUESTIONS = [
  {
    "id": "imp_1782990624735_0",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "源文件扩展名为?编译生成字节码文件扩展名为?",
    "options": [],
    "answer": "源文件扩展名为 .java；编译生成字节码文件扩展名为 .class",
    "explanation": ""
  },
  {
    "id": "imp_1782990624735_1",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "行注释、块注释、文档注释分别怎么标注?",
    "options": [],
    "answer": "行注释：//；块注释：/* ... */；文档注释：/** ... */",
    "explanation": ""
  },
  {
    "id": "imp_1782990624735_2",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "编译源代码命令、运行字节码、显示JDK版本号、反编译字节码、生成文档注释的命令及格式",
    "options": [],
    "answer": "编译源代码：javac 源文件名.java 运行字节码：java 类名 显示JDK版本号：java -version 反编译字节码：javap 类名 生成文档注释：javadoc 源文件名.java",
    "explanation": ""
  },
  {
    "id": "imp_1782990624735_3",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "布尔型变量定义定义及取值",
    "options": [],
    "answer": "布尔型变量定义：boolean flag = true; 或 boolean flag = false;，取值只能是 true 或 false",
    "explanation": ""
  },
  {
    "id": "imp_1782990624735_4",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "面向对象三个特性",
    "options": [],
    "answer": "面向对象三个特性：封装、继承、多态",
    "explanation": ""
  },
  {
    "id": "imp_1782990624735_5",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "static class implements interface this super import package abstract final关键字用途",
    "options": [],
    "answer": "static：静态成员，属于类而非实例 class：定义类 implements：实现接口 interface：定义接口 this：当前对象引用 super：父类引用 import：导入包/类 package：声明包 abstract：抽象类/抽象方法 final：类不可继承、方法不可重写、变量为常量",
    "explanation": ""
  },
  {
    "id": "imp_1782990624736_6",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "类成员访问权限控制关键字",
    "options": [],
    "answer": "类成员访问权限控制关键字：private（本类）、default/缺省（同包）、protected（同包+子类）、public（任意）",
    "explanation": ""
  },
  {
    "id": "imp_1782990624736_7",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "多层继承构造函数执行过程",
    "options": [],
    "answer": "多层继承构造函数执行过程：从最顶层父类开始逐层向下执行，先执行 Object 构造，再执行中间父类构造，最后执行子类构造，子类构造默认首行调用 super()",
    "explanation": ""
  },
  {
    "id": "imp_1782990624736_8",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "兰波达表达式定义排序规则使用，如Arrays.sort(a,(01,02)->02-01),前面减后面为升序，后面减前面为降序",
    "options": [],
    "answer": "Lambda表达式排序：Arrays.sort(a, (o1, o2) -> o1 - o2) 前减后为升序；Arrays.sort(a, (o1, o2) -> o2 - o1) 后减前为降序",
    "explanation": ""
  },
  {
    "id": "imp_1782990624736_9",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "异常处理关键字",
    "options": [],
    "answer": "异常处理关键字：try、catch、finally、throw、throws",
    "explanation": ""
  },
  {
    "id": "imp_1782990624736_10",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "多线程主要方法及功能如sleep run start interrupt wait notify notifyAll等",
    "options": [],
    "answer": "多线程主要方法： sleep() 休眠指定毫秒 run() 线程执行体 start() 启动线程 interrupt() 中断线程 wait() 释放锁等待 notify() 唤醒一个等待线程 notifyAll() 唤醒所有等待线程",
    "explanation": ""
  },
  {
    "id": "imp_1782990624736_11",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "泛型容器类、拿来就用线程的使用格式统一的方法，支持泛型，TreeSet HashSet TreeMap HashMap LinkedList ArrayList BigInteger",
    "options": [],
    "answer": "泛型容器类： ArrayList 动态数组 LinkedList 双向链表 HashSet 无序不重复 TreeSet 有序不重复 HashMap 键值对无序 TreeMap 键值对有序 BigInteger 大整数 统一使用泛型格式如 ArrayList<String> list = new ArrayList<>()",
    "explanation": ""
  },
  {
    "id": "imp_1782990624736_12",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "文件字节流、字符流、缓冲流、数组流、字符串流",
    "options": [],
    "answer": "文件字节流：FileInputStream/FileOutputStream 字符流：FileReader/FileWriter 缓冲流：BufferedReader/BufferedWriter、BufferedInputStream/BufferedOutputStream 数组流：ByteArrayInputStream/ByteArrayOutputStream 字符串流：StringReader/StringWriter",
    "explanation": ""
  },
  {
    "id": "imp_1782990624736_13",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "文件序列化，把一个对象完全转成字节序列，不用考虑对象成员个数及类型，以整个对象、数组、LinkedList为单位读写文件",
    "options": [],
    "answer": "文件序列化：类实现 Serializable 接口，用 ObjectOutputStream 的 writeObject() 写入，ObjectInputStream 的 readObject() 读取，可整体读写对象、数组、LinkedList",
    "explanation": ""
  },
  {
    "id": "imp_1782990624736_14",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "为按钮等组件事件源，绑定监视器监听的方法addActionListener",
    "options": [],
    "answer": "为按钮等组件绑定监视器：button.addActionListener(listener);，监听器实现 ActionListener 接口，重写 actionPerformed(ActionEvent e) 方法",
    "explanation": ""
  },
  {
    "id": "imp_1782991704422_0",
    "type": "qa",
    "subject": "Java",
    "category": "编程题",
    "difficulty": 1,
    "question": "求平均值",
    "options": [],
    "answer": "(1)import java.util.Scanner; public class Exam{ public static void main(String argv[]){ Scanner sr=new Scanner(System.in); int i,s=0,a; for (i=1;i<=10;i++){ a=sr.nextInt(); s=s+a; } System.out.printf(\"%.2f\\n\",s/10.0); } } (2)import java.util.Scanner; public class Exam{ public static void main(String argv[]){ Scanner sr=new Scanner(System.in); double s=0,a; int gs=0; while(sr.hasNextDouble()){ a=sr.nextDouble(); s=s+a; gs++; } System.out.printf(\"%d个数的平均值为%.2f\\n\",gs,s/gs); } }",
    "explanation": ""
  },
  {
    "id": "imp_1782991704423_1",
    "type": "qa",
    "subject": "Java",
    "category": "编程题",
    "difficulty": 1,
    "question": "类的定义和使用",
    "options": [],
    "answer": "class DCSL{ int a,d,n; DCSL(int a,int d,int n){ this.a=a; this.d=d; this.n=n; } int getHe(){ return(2*a+(n-1)*d)/2*n; } } public class Exam { public static void main(String[] args) { DCSL sl=new DCSL(3,2,4); System.out.println(sl.getHe()); } }",
    "explanation": ""
  },
  {
    "id": "imp_1782991704423_2",
    "type": "qa",
    "subject": "Java",
    "category": "编程题",
    "difficulty": 1,
    "question": "类的继承（super）",
    "options": [],
    "answer": "class TX{ int a,b,c; TX(int a,int b,int c){ this.a=a; this.b=b; this.c=c; } double getArea(){ return (a+b)*c/2.0; } } class TXZ extends TX{ int h; TXZ(int a,int b,int c,int h){ super(a,b,c); this.h=h; } double getV(){ return getArea()*h; } } public class Exam { public static void main(String[] args) { TXZ z=new TXZ(1,2,3,4); System.out.printf (\"%.2f\\n\",z.getV()); } }",
    "explanation": ""
  },
  {
    "id": "imp_1782991704423_3",
    "type": "qa",
    "subject": "Java",
    "category": "编程题",
    "difficulty": 1,
    "question": "继承多态，抽象类",
    "options": [],
    "answer": "（继承）interface XS{ int getXS(); } class NX implements XS{ public int getXS(){ return 100000; } } class YX implements XS{ public int getXS(){ return 8000*12; } } class ZX implements XS{ public int getXS(){ return 1500*52; } } public class Exam { public static void main(String[] args) { XS s[]={new NX(),new YX(),new ZX()}; for(int i=0;i<=2;i++) System.out.println(s[i].getXS()); } } （抽象）abstract class XS{ abstract int getXS(); } class NX extends XS{ public int getXS(){ return 100000; } } class YX extends XS{ public int getXS(){ return 8000*12; } } class ZX extends XS{ public int getXS(){ return 1500*52; } } public class Exam { public static void main(String[] args) { XS s[]={new NX(),new YX(),new ZX()}; for(int i=0;i<=2;i++) System.out.println(s[i].getXS()); } }",
    "explanation": ""
  }
];
