var QUESTIONS = [
  {
    "id": "imp_1782990624735_0",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "源文件扩展名为?编译生成字节码文件扩展名为?",
    "options": [],
    "answer": "源文件扩展名为 .java；编译生成字节码文件扩展名为 .class",
    "explanation": ""
  },
  {
    "id": "imp_1782990624735_1",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "行注释、块注释、文档注释分别怎么标注?",
    "options": [],
    "answer": "行注释：//；块注释：/* ... */；文档注释：/** ... */",
    "explanation": ""
  },
  {
    "id": "imp_1782990624735_2",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "编译源代码命令、运行字节码、显示JDK版本号、反编译字节码、生成文档注释的命令及格式",
    "options": [],
    "answer": "编译源代码：javac 源文件名.java 运行字节码：java 类名 显示JDK版本号：java -version 反编译字节码：javap 类名 生成文档注释：javadoc 源文件名.java",
    "explanation": ""
  },
  {
    "id": "imp_1782990624735_3",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "布尔型变量定义定义及取值",
    "options": [],
    "answer": "布尔型变量定义：boolean flag = true; 或 boolean flag = false;，取值只能是 true 或 false",
    "explanation": ""
  },
  {
    "id": "imp_1782990624735_4",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "面向对象三个特性",
    "options": [],
    "answer": "面向对象三个特性：封装、继承、多态",
    "explanation": ""
  },
  {
    "id": "imp_1782990624735_5",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "static class implements interface this super import package abstract final关键字用途",
    "options": [],
    "answer": "static：静态成员，属于类而非实例 class：定义类 implements：实现接口 interface：定义接口 this：当前对象引用 super：父类引用 import：导入包/类 package：声明包 abstract：抽象类/抽象方法 final：类不可继承、方法不可重写、变量为常量",
    "explanation": ""
  },
  {
    "id": "imp_1782990624736_6",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "类成员访问权限控制关键字",
    "options": [],
    "answer": "类成员访问权限控制关键字：private（本类）、default/缺省（同包）、protected（同包+子类）、public（任意）",
    "explanation": ""
  },
  {
    "id": "imp_1782990624736_7",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "多层继承构造函数执行过程",
    "options": [],
    "answer": "多层继承构造函数执行过程：从最顶层父类开始逐层向下执行，先执行 Object 构造，再执行中间父类构造，最后执行子类构造，子类构造默认首行调用 super()",
    "explanation": ""
  },
  {
    "id": "imp_1782990624736_8",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "兰波达表达式定义排序规则使用，如Arrays.sort(a,(01,02)->02-01),前面减后面为升序，后面减前面为降序",
    "options": [],
    "answer": "Lambda表达式排序：Arrays.sort(a, (o1, o2) -> o1 - o2) 前减后为升序；Arrays.sort(a, (o1, o2) -> o2 - o1) 后减前为降序",
    "explanation": ""
  },
  {
    "id": "imp_1782990624736_9",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "异常处理关键字",
    "options": [],
    "answer": "异常处理关键字：try、catch、finally、throw、throws",
    "explanation": ""
  },
  {
    "id": "imp_1782990624736_10",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "多线程主要方法及功能如sleep run start interrupt wait notify notifyAll等",
    "options": [],
    "answer": "多线程主要方法： sleep() 休眠指定毫秒 run() 线程执行体 start() 启动线程 interrupt() 中断线程 wait() 释放锁等待 notify() 唤醒一个等待线程 notifyAll() 唤醒所有等待线程",
    "explanation": ""
  },
  {
    "id": "imp_1782990624736_11",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "泛型容器类、拿来就用线程的使用格式统一的方法，支持泛型，TreeSet HashSet TreeMap HashMap LinkedList ArrayList BigInteger",
    "options": [],
    "answer": "泛型容器类： ArrayList 动态数组 LinkedList 双向链表 HashSet 无序不重复 TreeSet 有序不重复 HashMap 键值对无序 TreeMap 键值对有序 BigInteger 大整数 统一使用泛型格式如 ArrayList<String> list = new ArrayList<>()",
    "explanation": ""
  },
  {
    "id": "imp_1782990624736_12",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "文件字节流、字符流、缓冲流、数组流、字符串流",
    "options": [],
    "answer": "文件字节流：FileInputStream/FileOutputStream 字符流：FileReader/FileWriter 缓冲流：BufferedReader/BufferedWriter、BufferedInputStream/BufferedOutputStream 数组流：ByteArrayInputStream/ByteArrayOutputStream 字符串流：StringReader/StringWriter",
    "explanation": ""
  },
  {
    "id": "imp_1782990624736_13",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "文件序列化，把一个对象完全转成字节序列，不用考虑对象成员个数及类型，以整个对象、数组、LinkedList为单位读写文件",
    "options": [],
    "answer": "文件序列化：类实现 Serializable 接口，用 ObjectOutputStream 的 writeObject() 写入，ObjectInputStream 的 readObject() 读取，可整体读写对象、数组、LinkedList",
    "explanation": ""
  },
  {
    "id": "imp_1782990624736_14",
    "type": "qa",
    "subject": "Java",
    "category": "",
    "difficulty": 1,
    "question": "为按钮等组件事件源，绑定监视器监听的方法addActionListener",
    "options": [],
    "answer": "为按钮等组件绑定监视器：button.addActionListener(listener);，监听器实现 ActionListener 接口，重写 actionPerformed(ActionEvent e) 方法",
    "explanation": ""
  },
  {
    "id": "imp_1782991704422_0",
    "type": "qa",
    "subject": "Java",
    "category": "编程题",
    "difficulty": 1,
    "question": "求平均值",
    "options": [],
    "answer": "(1)import java.util.Scanner; public class Exam{ public static void main(String argv[]){ Scanner sr=new Scanner(System.in); int i,s=0,a; for (i=1;i<=10;i++){ a=sr.nextInt(); s=s+a; } System.out.printf(\"%.2f\\n\",s/10.0); } } (2)import java.util.Scanner; public class Exam{ public static void main(String argv[]){ Scanner sr=new Scanner(System.in); double s=0,a; int gs=0; while(sr.hasNextDouble()){ a=sr.nextDouble(); s=s+a; gs++; } System.out.printf(\"%d个数的平均值为%.2f\\n\",gs,s/gs); } }",
    "explanation": ""
  },
  {
    "id": "imp_1782991704423_1",
    "type": "qa",
    "subject": "Java",
    "category": "编程题",
    "difficulty": 1,
    "question": "类的定义和使用",
    "options": [],
    "answer": "class DCSL{ int a,d,n; DCSL(int a,int d,int n){ this.a=a; this.d=d; this.n=n; } int getHe(){ return(2*a+(n-1)*d)/2*n; } } public class Exam { public static void main(String[] args) { DCSL sl=new DCSL(3,2,4); System.out.println(sl.getHe()); } }",
    "explanation": ""
  },
  {
    "id": "imp_1782991704423_2",
    "type": "qa",
    "subject": "Java",
    "category": "编程题",
    "difficulty": 1,
    "question": "类的继承（super）",
    "options": [],
    "answer": "class TX{ int a,b,c; TX(int a,int b,int c){ this.a=a; this.b=b; this.c=c; } double getArea(){ return (a+b)*c/2.0; } } class TXZ extends TX{ int h; TXZ(int a,int b,int c,int h){ super(a,b,c); this.h=h; } double getV(){ return getArea()*h; } } public class Exam { public static void main(String[] args) { TXZ z=new TXZ(1,2,3,4); System.out.printf (\"%.2f\\n\",z.getV()); } }",
    "explanation": ""
  },
  {
    "id": "imp_1782991704423_3",
    "type": "qa",
    "subject": "Java",
    "category": "编程题",
    "difficulty": 1,
    "question": "继承多态，抽象类",
    "options": [],
    "answer": "（继承）interface XS{ int getXS(); } class NX implements XS{ public int getXS(){ return 100000; } } class YX implements XS{ public int getXS(){ return 8000*12; } } class ZX implements XS{ public int getXS(){ return 1500*52; } } public class Exam { public static void main(String[] args) { XS s[]={new NX(),new YX(),new ZX()}; for(int i=0;i<=2;i++) System.out.println(s[i].getXS()); } } （抽象）abstract class XS{ abstract int getXS(); } class NX extends XS{ public int getXS(){ return 100000; } } class YX extends XS{ public int getXS(){ return 8000*12; } } class ZX extends XS{ public int getXS(){ return 1500*52; } } public class Exam { public static void main(String[] args) { XS s[]={new NX(),new YX(),new ZX()}; for(int i=0;i<=2;i++) System.out.println(s[i].getXS()); } }",
    "explanation": ""
  },
  {
    "id": "mg_1",
    "type": "multiple",
    "subject": "毛概",
    "category": "多选题",
    "difficulty": 1,
    "question": "马克思主义中国化时代化，就是立足中国国情和时代特点，坚持把马克思主义基本原理同    相结合、同    相结合，深入研究和解决中国革命、建设、改革不同历史时期的实际问题，真正搞懂面临的时代课题，创造新的理论成果。",
    "options": ["改革开放实践","中国具体实际","中华优秀传统文化","世界具体实际"],
    "answer": [1,2],
    "explanation": ""
  },
  {
    "id": "mg_2",
    "type": "multiple",
    "subject": "毛概",
    "category": "多选题",
    "difficulty": 1,
    "question": "党的十八大以来，中国特色社会主义进入新时代，以习近平同志为主要代表的中国共产党人，提出一系列原创性的治国理政新理念新思想新战略，主要系统回答新时代哪些重大时代课题?",
    "options": ["坚持和发展什么样的中国特色社会主义、怎样坚持和发展中国特色社会主义","建设什么样的社会主义现代化强国、怎样建设社会主义现代化强国","建设什么样的党、怎样建设党，实现什么样的发展、怎样发展","建设什么样的长期执政的马克思主义政党、怎样建设长期执政的马克思主义政党"],
    "answer": [0,1,3],
    "explanation": ""
  },
  {
    "id": "mg_3",
    "type": "multiple",
    "subject": "毛概",
    "category": "多选题",
    "difficulty": 1,
    "question": "在马克思主义中国化时代化的历史进程中，产生了毛泽东思想、( )等理论成果。",
    "options": ["邓小平理论","科学发展观","\u201c三个代表\u201d重要思想","习近平新时代中国特色社会主义思想"],
    "answer": [0,1,2,3],
    "explanation": ""
  },
  {
    "id": "mg_4",
    "type": "multiple",
    "subject": "毛概",
    "category": "多选题",
    "difficulty": 1,
    "question": "为什么推进马克思主义中国化时代化，是有以下两个原因，一是    ，二是     。",
    "options": ["历史上曾犯过教条主义、经验主义错误","马克思主义理论解决了俄国实际问题","解决中国实际问题的客观需要","马克思主义理论本身发展的内在要求"],
    "answer": [2,3],
    "explanation": ""
  },
  {
    "id": "mg_5",
    "type": "multiple",
    "subject": "毛概",
    "category": "多选题",
    "difficulty": 1,
    "question": "毛泽东思想既包括关于( )的正确思想，也包括关于社会主义建设的正确思想。",
    "options": ["改革开放","中国特色社会主义建设","社会主义革命","新民主主义革命"],
    "answer": [2,3],
    "explanation": ""
  },
  {
    "id": "mg_6",
    "type": "multiple",
    "subject": "毛概",
    "category": "多选题",
    "difficulty": 1,
    "question": "大学生要坚持理论联系实际，紧密联系( )、中华民族发展史，紧密联系自己的思想实际，把理论与实践、理想与现实、主观与客观、知与行有机统一起来，自觉投身于中国特色社会主义伟大实践，为实现中华民族伟大复兴作出应有贡献。",
    "options": ["改革开放史","社会主义发展史","新中国史","党史"],
    "answer": [0,1,2,3],
    "explanation": ""
  },
  {
    "id": "mg_7",
    "type": "multiple",
    "subject": "毛概",
    "category": "多选题",
    "difficulty": 1,
    "question": "大学生要坚持理论联系实际，紧密结合( )的伟大实践，自觉投身于中国特色社会主义伟大实践，为实现中华民族伟大复兴作出应有贡献。",
    "options": ["推进伟大事业","进行伟大斗争","实现伟大梦想","建设伟大工程"],
    "answer": [0,1,2,3],
    "explanation": ""
  },
  {
    "id": "mg_8",
    "type": "multiple",
    "subject": "毛概",
    "category": "多选题",
    "difficulty": 1,
    "question": "我们要坚定中国特色社会主义( )，增进政治认同、思想认同、情感认同。",
    "options": ["文化自信","道路自信","制度自信","理论自信"],
    "answer": [0,1,2,3],
    "explanation": ""
  },
  {
    "id": "mg_9",
    "type": "multiple",
    "subject": "毛概",
    "category": "多选题",
    "difficulty": 1,
    "question": "中国共产党以    、毛泽东思想、邓小平理论、\u201c三个代表\u201d重要思想、科学发展观、    作为自己的指导思想和行动指南。",
    "options": ["习近平新时代中国特色社会主义思想","马克思列宁主义","中国特色社会主义理论","新民主主义革命理论"],
    "answer": [0,1],
    "explanation": ""
  },
  {
    "id": "mg_10",
    "type": "multiple",
    "subject": "毛概",
    "category": "多选题",
    "difficulty": 1,
    "question": "( )是毛泽东思想活的灵魂，这一具有中国共产党人特色的立场、观点和方法也贯穿于中国特色社会主义理论体系之中。",
    "options": ["独立自主","群众路线","与时俱进","实事求是"],
    "answer": [0,1,3],
    "explanation": ""
  },
  {
    "id": "mg_11",
    "type": "multiple",
    "subject": "毛概",
    "category": "多选题",
    "difficulty": 1,
    "question": "在新民主主义革命时期，以毛泽东同志为主要代表的中国共产党人，把马克思列宁主义基本原理同中国具体实际结合起来，对经过艰苦探索、付出巨大牺牲积累的一系列独创性经验作了理论概括，开辟了( )的正确革命道路。",
    "options": ["独立自主","武装夺取政权","统一战线","农村包围城市"],
    "answer": [1,3],
    "explanation": ""
  },
  {
    "id": "mg_12",
    "type": "multiple",
    "subject": "毛概",
    "category": "多选题",
    "difficulty": 1,
    "question": "坚持和发展马克思主义，必须同中国具体实际相结合，着眼解决革命、建设、改革中的实际问题，不断回答( )，作出符合中国实际和时代要求的正确回答，得出符合客观规律的科学认识，形成与时俱进的理论成果，更好指导中国实践。",
    "options": ["世界之问","时代之问","中国之问","人民之问"],
    "answer": [0,1,2,3],
    "explanation": ""
  },
  {
    "id": "mg_13",
    "type": "multiple",
    "subject": "毛概",
    "category": "多选题",
    "difficulty": 1,
    "question": "准确把握马克思主义中国化时代化的科学内涵，要做    与    相统一。",
    "options": ["坚持马克思主义","体现马克思主义","照搬马克思主义","发展马克思主义"],
    "answer": [0,3],
    "explanation": ""
  },
  {
    "id": "mg_14",
    "type": "multiple",
    "subject": "毛概",
    "category": "多选题",
    "difficulty": 1,
    "question": "中国共产党高举中国特色社会主义伟大旗帜，团结带领中国人民，解放思想、锐意进取，创造了改革开放和社会主义现代化建设的伟大成就，我国",
    "options": ["实现了从生产力相对落后的状况到经济总量跃居世界第二的历史性突破","实现了人民生活从温饱不足到总体小康、奔向全面小康的历史性跨越","为实现中华民族伟大复兴提供了充满新的活力的体制保证和快速发展的物质条件","推进了中华民族从站起来到富起来的伟大飞跃"],
    "answer": [0,1,2,3],
    "explanation": ""
  },
  {
    "id": "mg_15",
    "type": "multiple",
    "subject": "毛概",
    "category": "多选题",
    "difficulty": 1,
    "question": "坚持马克思主义，最重要的是坚持马克思主义基本原理和贯穿其中的( )，坚定不移坚持马克思主义指导地位，任何时候任何情况下都不动摇。",
    "options": ["立场","观点","方法","规则"],
    "answer": [0,1,2],
    "explanation": ""
  },
  {
    "id": "mg_16",
    "type": "judge",
    "subject": "毛概",
    "category": "判断题",
    "difficulty": 1,
    "question": "第一次提出\u201c马克思主义中国化\u201d命题的会议是1938年党的六届六中全会。",
    "options": ["对","错"],
    "answer": [0],
    "explanation": ""
  },
  {
    "id": "mg_17",
    "type": "judge",
    "subject": "毛概",
    "category": "判断题",
    "difficulty": 1,
    "question": "中共十一届三中全会的召开，实现了新中国成立以来党的历史上具有深远意义的伟大转折，开启了改革开放和社会主义现代化建设历史新时期。",
    "options": ["对","错"],
    "answer": [0],
    "explanation": ""
  },
  {
    "id": "mg_18",
    "type": "judge",
    "subject": "毛概",
    "category": "判断题",
    "difficulty": 1,
    "question": "历史和现实反复证明,马克思主义只有中国化时代化才能在中国大地上闪耀真理光芒,也只有实现中国化时代化才能救中国、发展中国,才能实现中华民族的伟大复兴。",
    "options": ["对","错"],
    "answer": [0],
    "explanation": ""
  },
  {
    "id": "mg_19",
    "type": "judge",
    "subject": "毛概",
    "category": "判断题",
    "difficulty": 1,
    "question": "中国共产党从成立之日起，就明确把马克思列宁主义确立为指导思想。",
    "options": ["对","错"],
    "answer": [0],
    "explanation": ""
  },
  {
    "id": "mg_20",
    "type": "judge",
    "subject": "毛概",
    "category": "判断题",
    "difficulty": 1,
    "question": "1945年，在党的七大上，毛泽东代表党中央作了《改造我们的学习》。",
    "options": ["对","错"],
    "answer": [1],
    "explanation": ""
  },
  {
    "id": "mg_21",
    "type": "judge",
    "subject": "毛概",
    "category": "判断题",
    "difficulty": 1,
    "question": "习近平总书记深刻指出,\u201c马克思主义之所以行,就在于党不断推进马克思主义中国化时代化并用以指导实践\u201d。",
    "options": ["对","错"],
    "answer": [0],
    "explanation": ""
  },
  {
    "id": "mg_22",
    "type": "judge",
    "subject": "毛概",
    "category": "判断题",
    "difficulty": 1,
    "question": "2021年，党的十九届六中全会通过的《中共中央关于党的百年奋斗重大成就和历史经验的决议》总结了百年来中国共产党推进马克思主义中国化时代化的重大成就，阐释了马克思主义中国化时代化的重大历史意义。",
    "options": ["对","错"],
    "answer": [0],
    "explanation": ""
  },
  {
    "id": "mg_23",
    "type": "judge",
    "subject": "毛概",
    "category": "判断题",
    "difficulty": 1,
    "question": "党的二十大明确把\u201c不断谱写马克思主义中国化时代化新篇章\u201d作为当代中国共产党人的庄严历史责任，并提出了继续推进马克思主义中国化时代化的新要求。",
    "options": ["对","错"],
    "answer": [0],
    "explanation": ""
  },
  {
    "id": "mg_24",
    "type": "judge",
    "subject": "毛概",
    "category": "判断题",
    "difficulty": 1,
    "question": "推进马克思主义中国化时代化，是马克思主义理论本身发展的内在要求。",
    "options": ["对","错"],
    "answer": [0],
    "explanation": ""
  },
  {
    "id": "mg_25",
    "type": "judge",
    "subject": "毛概",
    "category": "判断题",
    "difficulty": 1,
    "question": "推进马克思主义中国化时代化，是解决中国实际问题的客观需要。",
    "options": ["对","错"],
    "answer": [0],
    "explanation": ""
  },
  {
    "id": "mg_26",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "( )给中国送来了马克思列宁主义，给苦苦探寻救亡图存出路的中国人民指明了前进方向、提供了全新选择。",
    "options": ["五四运动","新文化运动","十月革命","鸦片战争"],
    "answer": 2,
    "explanation": ""
  },
  {
    "id": "mg_27",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "中国共产党从成立之日起，就明确把( )确立为指导思想。",
    "options": ["邓小平理论","\u201c三个代表\u201d重要思想","马克思列宁主义","毛泽东思想"],
    "answer": 2,
    "explanation": ""
  },
  {
    "id": "mg_28",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "1945年，在党的七大上，( )代表党中央作了《关于修改党章的报告》，对马克思主义中国化从理论上作了进一步的阐述，并指出毛泽东思想是\u201c中国化的马克思主义\u201d。",
    "options": ["任弼时","周恩来","毛泽东","刘少奇"],
    "answer": 3,
    "explanation": ""
  },
  {
    "id": "mg_29",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "1938年，毛泽东在党的六届六中全会上作了《论新阶段》的报告，强调:\u201c没有抽象的马克思主义，只有具体的马克思主义。\u2026\u2026马克思主义的中国化，使之在其每一表现中带着中国的特性，即是说，按照中国的特点去应用它，成为全党亟待了解并亟须解决的问题。\u201d这标志着( )这一命题的正式提出。",
    "options": ["新民主主义革命理论","新民主主义革命路线","毛泽东思想","马克思主义中国化"],
    "answer": 3,
    "explanation": ""
  },
  {
    "id": "mg_30",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "党的十八大以来，以习近平同志为核心的党中央明确提出要不断推进( )。",
    "options": ["马克思主义中国化时代化","\u201c两个结合\u201d","社会主义现代化","社会主义现代化强国"],
    "answer": 0,
    "explanation": ""
  },
  {
    "id": "mg_31",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "2021年，党的( )通过的《中共中央关于党的百年奋斗重大成就和历史经验的决议》总结了百年来中国共产党推进马克思主义中国化时代化的重大成就，阐释了马克思主义中国化时代化的重大历史意义。",
    "options": ["党的十八大","党的十九届六中全会","党的十八届三中全会","党的十九大"],
    "answer": 1,
    "explanation": ""
  },
  {
    "id": "mg_32",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "( )明确把\u201c不断谱写马克思主义中国化时代化新篇章\u201d作为当代中国共产党人的庄严历史责任，并提出了继续推进马克思主义中国化时代化的新要求。",
    "options": ["党的十七大","党的二十大","党的十八大","党的十九大"],
    "answer": 1,
    "explanation": ""
  },
  {
    "id": "mg_33",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "把马克思主义基本原理同中国具体实际相结合、同中华优秀传统文化相结合，也就是如何实现马克思主义( )的问题。",
    "options": ["中国化现代化","时代化","中国化时代化","中国化大众化"],
    "answer": 2,
    "explanation": ""
  },
  {
    "id": "mg_34",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "( )是马克思主义中国化时代化的第一次历史性飞跃。",
    "options": ["邓小平理论","毛泽东思想","\u201c三个代表\u201d重要思想","科学发展观"],
    "answer": 1,
    "explanation": ""
  },
  {
    "id": "mg_35",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "马克思主义中国化时代化的理论成果是一脉相承又( )的关系。",
    "options": ["独立自主","与时俱进","精益求精","实事求是"],
    "answer": 1,
    "explanation": ""
  },
  {
    "id": "mg_36",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "正是由于中国共产党坚持( )的思想路线，才能够在实践中开创中国特色社会主义道路，形成中国特色社会主义理论体系。",
    "options": ["党的建设","实事求是","与时俱进","统一战线"],
    "answer": 1,
    "explanation": ""
  },
  {
    "id": "mg_37",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "( )是中国特色社会主义理论体系的开篇之作。",
    "options": ["科学发展观","毛泽东思想","\u201c三个代表\u201d重要思想","邓小平理论"],
    "answer": 3,
    "explanation": ""
  },
  {
    "id": "mg_38",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "在( )，中国共产党坚持以理论创新引领事业发展，从新的实践和时代特征出发坚持和发展马克思主义，科学回答了建设中国特色社会主义的发展道路、发展阶段、根本任务、发展动力、发展战略等一系列基本问题，形成中国特色社会主义理论体系，实现了马克思主义中国化时代化新的飞跃。",
    "options": ["社会主义现代化建设新时期","改革开放和社会主义现代化建设新时期","改革开放","社会主义建设时期"],
    "answer": 1,
    "explanation": ""
  },
  {
    "id": "mg_39",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "社会主义民主政治的本质要求是( )。",
    "options": ["人民当家作主","依法治国","坚持党的领导","实行改革开放"],
    "answer": 0,
    "explanation": ""
  },
  {
    "id": "mg_40",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "实践证明，中国共产党为什么能，中国特色社会主义为什么好，归根到底是中国化时代化的( )。",
    "options": ["社会主义行","马克思主义行","社会主义好","马克思主义好"],
    "answer": 1,
    "explanation": ""
  },
  {
    "id": "mg_41",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "中国特色社会主义理论体系始终坚持将( )作为根本工作路线。",
    "options": ["与时俱进","独立自主","实事求是","群众路线"],
    "answer": 3,
    "explanation": ""
  },
  {
    "id": "mg_42",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "毛泽东思想形成的时代条件是( )。",
    "options": ["1927年以后中国共产党独立担负起领导中国革命的重任","1919年以后中国革命进入新民主主义革命时期","19世纪末20世纪初，世界进入帝国主义和无产阶级革命时代","1840年以后中国成为一个半殖民地半封建社会"],
    "answer": 2,
    "explanation": ""
  },
  {
    "id": "mg_43",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "党的( )提出了\u201c中国特色社会主义理论体系\u201d的科学概念。",
    "options": ["十九大","十七大","十八大","二十大"],
    "answer": 1,
    "explanation": ""
  },
  {
    "id": "mg_44",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "毛泽东创造性地理论与实践的相结合、自我批评、( )的中国共产党三大工作作风。",
    "options": ["艰苦奋斗","惩前毖后、治病救人","谦虚谨慎、不骄不躁","和人民群众紧密地联系在一起"],
    "answer": 3,
    "explanation": ""
  },
  {
    "id": "mg_45",
    "type": "single",
    "subject": "毛概",
    "category": "单选题",
    "difficulty": 1,
    "question": "中共十一届三中全会以后，对毛泽东和毛泽东思想的历史地位作出科学的、实事求是的评价的历史文献是( )。",
    "options": ["《中国共产党中央委员会关于建国以来党的若干历史问题的决议》","《关于若干历史问题的决议》","《解放思想，实事求是，团结一致向前看》","《中共中央关于党的百年奋斗重大成就和历史经验的决议》"],
    "answer": 0,
    "explanation": ""
  }
];
